name: renttas
description: "A new Flutter project."



version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  onboarding: ^4.0.2
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  google_fonts: ^6.2.1
  intl_phone_field: ^3.2.0
  rate: ^0.0.2
  flutter_pannable_rating_bar: ^2.7.2+1
  url_launcher: ^6.3.0
  intl: ^0.19.0
  file_picker: ^8.0.5
  flutter_pdfview: ^1.3.2
  flutter_launcher_icons: "^0.9.2"
  flutter_bloc: ^8.1.6
  http: ^1.2.1
  flutter_pin_code_fields: ^2.2.0
  shared_preferences: ^2.2.3
  bloc: ^8.1.4
  meta: ^1.11.0
  uuid: ^4.4.0
  get: ^4.6.6
  flutter_phone_direct_caller: ^2.1.1
  image_picker: ^1.1.2
  path: ^1.8.0
  change_app_package_name: ^1.3.0
  firebase_core: ^3.2.0
  cloud_firestore: ^5.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
